# Generated by Django 3.1.4 on 2020-12-24 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ativo', '0001_initial'),
        ('capital', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='capital',
            name='ativo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ativo.ativo'),
            preserve_default=False,
        ),
    ]
