# Generated by Django 3.1.4 on 2020-12-24 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capital', '0002_capital_ativo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='capital',
            old_name='especie',
            new_name='valor',
        ),
    ]
