# Generated by Django 3.1.4 on 2020-12-23 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('historico', '0003_auto_20201222_0813'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historico',
            old_name='aumenta',
            new_name='aumentou',
        ),
    ]
