# Generated by Django 3.1.4 on 2020-12-23 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('historico', '0004_auto_20201222_2218'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historico',
            old_name='aumentou',
            new_name='previsao',
        ),
    ]
