# Generated by Django 3.1.4 on 2020-12-23 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historico', '0005_auto_20201222_2352'),
    ]

    operations = [
        migrations.AddField(
            model_name='historico',
            name='acertou',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
