# Generated by Django 3.1.4 on 2020-12-24 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historico', '0006_historico_acertou'),
    ]

    operations = [
        migrations.AddField(
            model_name='historico',
            name='variacao',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
    ]
